#!/bin/bash
#use in cronetab:
#*/10 * * * * /usr/local/ping-list/ping-list

LOG_FILE='/var/log/d71_fork_ping.log'

LOG_G_FILE='/var/log/d71_make_graph.log'

DATE_NOW=`/bin/date +%Y%m%d_%H%M%S`

echo $DATE_NOW > $LOG_FILE
/usr/local/ping-list/fork_ping /usr/local/ping-list/0.conf >> $LOG_FILE

echo $DATE_NOW > $LOG_G_FILE
/usr/local/ping-list/make_graph /usr/local/ping-list/graph.conf>> $LOG_G_FILE

